export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILED = "PRODUCT_LIST_FAILED";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAILED = "PRODUCT_DETAILS_FAILED";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILED = "CREATE_PRODUCT_FAILED";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";

export const PRODUCT_ADD_REVIEW_REQUEST = "PRODUCT_ADD_REVIEW_REQUEST";
export const PRODUCT_ADD_REVIEW_SUCCESS = "PRODUCT_ADD_REVIEW_SUCCESS";
export const PRODUCT_ADD_REVIEW_FAILED = "PRODUCT_ADD_REVIEW_FAILED";
export const PRODUCT_ADD_REVIEW_RESET = "PRODUCT_ADD_REVIEW_RESET";
